## If you want to use one of the kitchen-docker* drivers...
## You should rename this file to: .kitchen.local.yml
## OR:
##   export KITCHEN_LOCAL_YAML=.kitchen.docker.local.yml
## Hint: Make sure you have kitchen-docker and kitchen-docker-api gems installed
## Then set DOCKER_HOST=tcp://my-docker-host.example.com:4243
---
## driver name: docker is for portertech/kitchen-docker
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

platforms:
- name: centos-6.5
  driver_config:
    image: learndocker/centos
    platform: centos
- name: centos-6.9
- name: centos-7
  driver_config:
    run_command: /usr/sbin/init
    run_options:
      - volume: "/sys/fs/cgroup:/sys/fs/cgroup"
      - "--privileged"
## Precise Pangolin (LTS)
- name: ubuntu-12.04
## Trusty Tahr LTS ## HWE August 2016
- name: ubuntu-14.04
## Xenial Xerus ## EOL April 2021
- name: ubuntu-16.04
