## If you want to use one of the kitchen-docker* drivers...
## You should rename this file to: .kitchen.local.yml
## OR:
##   export KITCHEN_LOCAL_YAML=.kitchen.docker.local.yml
## Hint: Make sure you have kitchen-docker and kitchen-docker-api gems installed
## Then set DOCKER_HOST=tcp://my-docker-host.example.com:4243
---
## driver name: docker is for portertech/kitchen-docker
driver:
  name: docker
## https://github.com/test-kitchen/kitchen-docker/issues/54
  use_sudo: false

transport:
  name: sftp

platforms:
#- name: centos-5.10
#  driver_config:
#    image: cpuguy83/centos
#    platform: centos
#    provision_command:
#      - curl -L https://www.opscode.com/chef/install.sh | bash
#      - yum -y install make gcc which bash tar cronie
- name: centos-6.5
  driver_config:
    image: learndocker/centos
    platform: centos
    ## NOTE: Sadly this is to clean up the mess that is pip on RHEL 6.x
    ## Reference: https://github.com/neillturner/omnibus-ansible/issues/9
    provision_command: &1
      - &OMNIBUS_CHEF curl -L https://www.opscode.com/chef/install.sh | bash
      - sudo -E yum -y install libselinux-python python2-devel git python-setuptools python-setuptools-dev libffi-devel libssl-devel openssl-devel
      - sudo -E easy_install -i https://pypi.python.org/simple pip==1.2.1
      - sudo -E PIP_INDEX_URL=https://pypi.python.org/simple/  pip install --upgrade pip
      - sudo -E yum -y groupinstall 'Development Tools'
      - sudo -E pip install requests[security] urllib3[secure]
      - curl -Ls https://raw.githubusercontent.com/neillturner/omnibus-ansible/master/ansible_install.sh | bash

- name: centos-6.9
  driver_config:
    platform: centos
    provision_command: *1
- name: centos-7
  driver_config: &2
    run_command: /usr/sbin/init
    run_options:
      - volume: "/sys/fs/cgroup:/sys/fs/cgroup"
      - "--privileged"
## Precise Pangolin (LTS)
## NOTE: We also need to clean up old version of pip mess here too
#       (broke due to pypi switching to HTTPS, but they hardcoded HTTP!)
- name: ubuntu-12.04
  driver_config:
    provision_command: &3
      - *OMNIBUS_CHEF
      - sudo -E apt-get -y install git python python-setuptools python-pip build-essential python-dev libffi-dev libssl-dev
      - sudo -E easy_install -i https://pypi.python.org/simple pip==1.2.1
      - sudo -E PIP_INDEX_URL=https://pypi.python.org/simple/  pip install --upgrade pip
      - sudo -E pip install -U setuptools
      - sudo -E pip install jinja2 pyyaml

## Trusty Tahr LTS ## HWE August 2016
- name: ubuntu-14.04
  driver_config:
    provision_command: &4
      - *OMNIBUS_CHEF
      - sudo -E apt-get -y install git python python-setuptools python-pip build-essential python-dev libffi-dev libssl-dev
      - sudo -E easy_install pip
      - sudo -E pip install --upgrade pip
      - sudo -E pip install -U setuptools
      - sudo -E pip install jinja2 pyyaml
## Xenial Xerus ## EOL April 2021
- name: ubuntu-16.04
  driver_config:
    provision_command: *4
